### PR TITLE
Post

### PR DESCRIPTION
**Pull request by ragini07**
create a text based post from home page
edit and delete user posts

### CODE REVIEW

**Review by JowelTisso — APPROVED** [review]
* Clean code
* Good file structure
* Looks good to merge

**Review by manismk — APPROVED** [review]
Good naming convention.
Functionality works properly.

Remove console.logs and in Explore page the console.log is keep on happening never stopping.

**Comment by rahulmistry751** [comment]
Empty post can be added. Include condition to check whether user has given input or not in.

**Review by rahulmistry751 — APPROVED** [review]
Good Code UI and structure

**Comment by ragini07** [comment]
> Good naming convention. Functionality works properly.
> 
> Remove console.logs and in Explore page the console.log is keep on happening never stopping.



> Good naming convention. Functionality works properly.
> 
> Remove console.logs and in Explore page the console.log is keep on happening never stopping.

**Comment by ragini07** [comment]
> > Good naming convention. Functionality works properly.
> > Remove console.logs and in Explore page the console.log is keep on happening never stopping.
> 
> > Good naming convention. Functionality works properly.
> > Remove console.logs and in Explore page the console.log is keep on happening never stopping.

**Pull request merged**
